          function navNext()
          {
            for (temp = 0; temp <= 11 ; temp++)
            {
              document.getElementById('canvas'+temp).style.visibility="hidden";
            }

            simsubscreennum+=1;

            document.getElementById('canvas'+(simsubscreennum)).style.visibility="visible";
            document.getElementById('nextButton').style.visibility="hidden";
            magic();
          }

          var ca;
          var questions = [
          "In power characteristics curve fan, power refer to________",
          "In backward bladed fan, number of blades varies from________"
          ];

          var options2 = [
          ["Power generated by fan", "Brake horse power of prime mover", "Both a & b", "None of the above"], //Brake horse power of prime mover
          ["32-66", "14-24", "10-20", "None of the above"], //14-24

          ];

          function validateAnswer(qn, ans, left, top){
            $("#answer").empty();
            document.getElementById("a").innerHTML = "";
            document.getElementById("questDiv").style = "position:absolute;text-align:justify; font-size:14px; background-color:grey; color:white; padding:7.5px; border-radius:5px; visibility:visible; left:" + left + ";top:" + top + ";";
            document.getElementById("q").innerHTML = questions[qn];
            if (qn === 0) document.getElementById('questDiv').style.width = "370px";
            if (qn === 1) document.getElementById('questDiv').style.width = "250px";
            if (qn === 2) document.getElementById('questDiv').style.width = "250px";

            el = document.createElement("option");
            el.textContent = " ";
            el.value = " ";
            answer.appendChild(el);

            for (j = 0; j < options2[qn].length; j++) {
              opt = options2[qn][j];

              el = document.createElement("option");
              el.textContent = opt;
              el.value = opt;
              answer.appendChild(el);
              $("#answer").change(function() {
                ca = $(this).children("option:selected").val();
                if (options2[qn][ans] === ca) {
                  document.getElementById("a").innerHTML = "Correct Answer!";
                }
                else {
                  document.getElementById("a").innerHTML = "Wrong! Answer is " + options2[qn][ans];
                }
                setTimeout(function() {
                  document.getElementById("questDiv").style.visibility = "hidden";
                  document.getElementById("nextButton").style.visibility = "visible";
                }, 1500);
              });
            }
          }

          var p=Math.floor(Math.random()*(9));
          console.log(p);


            var data = [[12, 1.7, 8.06],
       [24, 3.2, 7.59],
       [30, 4.0, 7.59],
       ];

       var n;
       //for 300rpm at point 1
       var data1=[[0.45,17.6,17.1,0.5,18.6,16.4,2.2,18.3,16.8,1.5],
       [0.35,18.4,16.2,2.2,19.1,15.8,3.2,18,16.9,1.1],
       [0.3,19.1,15.6,3.5,19.7,15.2,4.5,17.2,16.9,0.3],
       [0.27,19.7,15.1,4.6,20,14.7,5.3,17.8,17.1,0.7],
       [0.235,19.7,15.2,4.5,19.9,15.1,4.8,17.7,17.1,0.6],
       [0.195,19.8,15.1,4.7,19.9,14.7,5.2,17.7,17.2,0.5],
       [0.17,20.1,15.1,5,20.2,14.6,5.6,17.6,17.4,0.2],
       [0.158,18.9,14.9,4,20.3,14.5,5.8,17.6,17.3,0.3],
       [0.12,20.1,15,5.1,20.3,14.7,5.6,17.5,17.3,0.2]];

       //for diameter of point1
       var data2=[[0.45,0.159,0.522,2.295,1.565],
       [0.35,0.096,2.295,3.338,1.148],
       [0.3,0.071,3.651,4.695,0.313],
       [0.27,0.051,4.799,5.529,0.730],
       [0.235,0.043,4.695,5.007,0.626],
       [0.195,0.030,4.903,5.424,0.522],
       [0.17,0.023,5.216,5.842,0.209],
       [0.158,0.020,4.173,6.051,0.313],
       [0.12,0.011,5.320,5.842,0.209]];

       var data2_1=[[1.615,0.257],
       [1.383,0.133],
       [0.722,0.051],
       [1.103,0.056],
       [1.021,0.044],
       [0.932,0.028],
       [0.590,0.013],
       [0.722,0.014],
       [0.590,0.007]];
      
       //for 400rpm at point 1
        var data3=[[0.45,17.7,16.9,0.8,18.5,16.1,2.5,19.1,15.6,3.5],
       [0.35,19.4,15.5,3.9,18.2,16.7,1.5,20.3,14.5,5.8],
       [0.3,20.4,14.4,6,17.9,16.7,1.2,21.2,13.6,7.6],
       [0.27,20.9,13.9,7,18,16.8,1.2,21.8,13.1,8.7],
       [0.235,21.1,13.7,7.4,17.8,17,0.8,21.7,13.2,8.5],
       [0.195,21.5,13.4,8.1,17.6,17.1,0.5,22,12.7,9.3],
       [0.17,21.7,13.2,8.5,17.6,17.2,0.4,22.1,12.9,9.2],
       [0.158,21.7,13.2,8.5,17.6,17.2,0.4,22.1,12.9,9.2],
       [0.12,21.6,13.3,8.3,17.6,17.2,0.4,21.2,13,8.2]];

        //for diameter of point2
        var data4=[[0.45,0.159,0.835,2.608,3.651],
       [0.35,0.096,0.096,4.069,1.565,6.051],
       [0.3,0.071,6.259,1.252,7.928],
       [0.27,0.051,7.303,1.252,9.076],
       [0.235,0.043,7.720,0.835,8.867],
       [0.195,0.030,8.450,0.522,9.389],
       [0.17,0.023,8.659,0.522,9.702],
       [0.158,0.020,8.867,0.417,9.598],
       [0.12,0.011,8.659,0.417,8.554]];

       var data11=[[45],
       [35],
       [30],
       [27],
       [23.5],
       [19.5],
       [17],
       [15.8],
       [12]];

       var data4_1=[[2.467,0.392],
       [3.176,0.305],
       [3.635,0.257],
       [3.889,0.199],
       [3.844,0.166],
       [3.956,0.118],
       [4.021,0.091],
       [4.000,0.078],
       [3.776,0.043]]

       var data5=[[0.522,2.295,1.565],
       [2.295,3.338,1.148],
       [3.651,4.695,0.313],
       [4.799,5.529,0.730],
       [4.695,5.007,0.626],
       [4.903,5.425,0.522],
       [5.216,5.842,0.209],
       [4.173,6.051,0.313],
       [5.320,5.842,0.209]];

       var data7=[[0.835,2.608,3.651],
       [4.069,1.565,6.051],
       [6.259,1.252,7.928],
       [7.303,1.252,9.076],
       [7.720,0.835,8.867],
       [8.450,0.522,9.389],
       [8.659,0.522,9.702],
       [8.867,0.417,9.598],
       [8.659,0.417,8.554]];

       var data8=[["data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"],
        ['Images/35 cm.png'],
        ['Images/30 cm.png'],
        ['Images/27 cm.png'], 
        ['Images/23.5 cm.png'],
        ['Images/19.5 cm.png'],
        ['Images/17 cm.png'],
        ['Images/15.8 cm.png'],
        ['Images/12 cm.png']];
          //-----------------------------------------blink arrow on the next step---------------------------------------------
          //blink arrow on the next step
          function animatearrow()
          {
            if (document.getElementById('arrow1').style.visibility==="hidden")
              document.getElementById('arrow1').style.visibility="visible";
            else
              document.getElementById('arrow1').style.visibility="hidden";
          }

          //stop blinking arrow
          function myStopFunction()
          {
            clearInterval(myInt);
            document.getElementById('arrow1').style.visibility="hidden";
          }



          var j0=0;
          function fillTable(repeat)
          {
            var tb1 = document.getElementById("table1");
            var row = tb1.insertRow();
            var cell = row.insertCell();
            cell.innerHTML =(repeat+1);
            for (i = 0; i <= data[j0].length-1; i++)
            {
              var cell = row.insertCell();
              cell.innerHTML = data[j0][i];
            }
            j0++;
          }
            var j1=0;
          function fillTable1(repeat)
          {
            var tb2 = document.getElementById("table2");
            var row2 = tb2.insertRow();
            for (i = 0; i <= data1[j1].length-1; i++)
            {
              var cell2 = row2.insertCell();
              cell2.innerHTML = data1[j1][i];
            }
            if(j1<=7)
            {
            j1++;
            fillTable1(j1);
            }
          }
            function highlight()
            {
              p=p+2;
            var rows = table2.getElementsByTagName("tr")[p];
            rows.style.backgroundColor = "#EFEDEF";
            }
              
            
          var j2=0;
          function fillTable2(repeat)
          {
            var tb3 = document.getElementById("table3");
            var row3 = tb3.insertRow();
            for (i = 0; i <= data2[j2].length-1; i++)
            {
              var cell3 = row3.insertCell();
              cell3.innerHTML = data2[j2][i];
            }
            if(j2<=7)
            {
            j2++;
            fillTable2(j2);
            }
          }

          function highlight1()
            {
              console.log(p);
              p=p+1;
            var rows = table3.getElementsByTagName("tr")[p];
            rows.style.backgroundColor = "#EFEDEF";
            }

            var j3=0;
          function fillTable3(repeat)
          {
            var tb4 = document.getElementById("table4");
            var row4 = tb4.insertRow();
            for (i = 0; i <= data3[j3].length-1; i++)
            {
              var cell4 = row4.insertCell();
              cell4.innerHTML = data3[j3][i];
            }
            if(j3<=7)
            {
            j3++;
            fillTable3(j3);
            }
          }
            function highlight2()
            {
            p=p+2;
            var rows = table4.getElementsByTagName("tr")[p];
            rows.style.backgroundColor = "#EFEDEF";
            }

          var j4=0;
          function fillTable4(repeat)
          {
            var tb5 = document.getElementById("table5");
            var row5 = tb5.insertRow();
            for (i = 0; i <= data2[j4].length-1; i++)
            {
              var cell5 = row5.insertCell();
              cell5.innerHTML = data2[j4][i];
            }
            if(j4<=7)
            {
            j4++;
            fillTable4(j4);
            }
          }
            function highlight3()
            {
            p=p+1;
            var rows = table5.getElementsByTagName("tr")[p];
            rows.style.backgroundColor = "#EFEDEF";
            }


          //-------------------------------------function magic starts here----------------------------------------------------
        function animateArrowATPosition(left,top,height,degg)
        {
         document.getElementById('arrow1').style="visibility:visible ;position:absolute; left:"+left+"px; top: "+top+"px; height:"+height+"px; z-index: 10;";
         document.getElementById("arrow1").style.WebkitTransform = "rotate("+degg+"deg)";
          // Code for IE9
         document.getElementById("arrow1").style.msTransform = "rotate("+degg+"deg)";
          // Standard syntax
         document.getElementById("arrow1").style.transform = "rotate("+degg+"deg)";
        }
        function magic()
        {
          if (simsubscreennum === 1) {
            myInt = setInterval(function () { animatearrow(); }, 500);
            animateArrowATPosition(245, 220, 20, 270);
            document.getElementById('x').style.visibility = "visible";
            document.getElementById("slider2").onclick = function () { step1(); };
          }
          if (simsubscreennum===2)
          {
            document.getElementById('switch2').style.visibility = "hidden";
            document.getElementById('Sample01').style.visibility = "hidden";
            document.getElementById('m11').style.display = "none";
            // document.getElementById('m').style.visibility = "hidden";
            document.getElementById('click1').style.visibility = "hidden";
            document.getElementById('circle2').style.visibility = "hidden";
            document.getElementById('arrow2').style.visibility = "hidden";
            document.getElementById('wind').style.visibility = "hidden";
            document.getElementById('speed').style.visibility = "hidden";
            document.getElementById('ndswh').style.visibility = "hidden";
            document.getElementById('x').style.visibility = "hidden";
            myInt = setInterval(function(){ animatearrow(); }, 500);
            animateArrowATPosition(580,340,30,-90);
            document.getElementById('manometer1').onclick=function() { step2(); };
          }
          if (simsubscreennum===3)
          {
            document.getElementById('scale').style.display="none";
            document.getElementById('table1').style.visibility="hidden";
            document.getElementById('ca-1').style.visibility="hidden";
            document.getElementById('ca-2').style.visibility="hidden";
            document.getElementById('ca-3').style.visibility="hidden";
            document.getElementById('30cm').style.visibility="hidden";
            document.getElementById('10').style.visibility = "visible";
            document.getElementById('ok').onclick = function() {
              document.getElementById('10').style.visibility = "hidden";
              document.getElementById('ok').style.visibility = "hidden";
              document.getElementById('a23').style.visibility="visible";
              document.getElementById('a22').style.visibility="visible";
              document.getElementById('scale').style.visibility="visible";

              myInt = setInterval(function(){ animatearrow(); }, 500);
              animateArrowATPosition(470,280,30,-90);
              document.getElementById('a22').onclick=function() { 
              myStopFunction();
              document.getElementById('a22').onclick="";
              document.getElementById('a24').style.visibility="visible";
              myInt = setInterval(function(){ animatearrow(); }, 500);
              animateArrowATPosition(540,370,30,-90);
              document.getElementById('a24').onclick=function() { 
                myStopFunction();
                document.getElementById('a24').onclick="";
                document.getElementById('a24').style.visibility="hidden";
                document.getElementById('a22').style.visibility="hidden";
                document.getElementById('a23').style.visibility="hidden";
                document.getElementById('can1').style.visibility="visible";
                document.getElementById('can2').style.visibility="visible";
                document.getElementById('can3').style.visibility="visible";
                document.getElementById('m-1').style.visibility="visible";
                document.getElementById('m-2').style.visibility="visible";
                document.getElementById('m-5').style.visibility="visible";
                document.getElementById('pipe1').style.visibility="visible";
                document.getElementById('ax1').style.visibility="visible";
                document.getElementById('ax2').style.visibility="visible";
                myInt = setInterval(function(){ animatearrow(); }, 500);
                animateArrowATPosition(490,160,30,360);
                document.getElementById('ax2').onclick=function() { 
                myStopFunction();
                document.getElementById('ax2').onclick="";
                document.getElementById('ab1').style.visibility="visible";
                myInt = setInterval(function(){ animatearrow(); }, 500);
                animateArrowATPosition(640,200,30,-90);
                document.getElementById('ab1').onclick=function() { 
                  myStopFunction();
                  document.getElementById('ab1').onclick="";
                  document.getElementById('m-1').style.visibility="hidden";
                  document.getElementById('m-2').style.visibility="hidden";
                  document.getElementById('m-5').style.visibility="hidden";
                  document.getElementById('can1').style.visibility="hidden";
                  document.getElementById('can2').style.visibility="hidden";
                  document.getElementById('can3').style.visibility="hidden";
                  
                  document.getElementById('ab1').style.visibility="hidden";
                  document.getElementById('samp1').style.visibility="visible";
                  document.getElementById('samp2').style.visibility="visible";
                  document.getElementById('img').style.visibility="visible";

                  document.getElementById('manotop').style.visibility="visible";
                  document.getElementById('mover1').style.visibility="visible";
                  setTimeout(function()
                  {
                    if(p==0)
                    {
                      document.getElementById('Sample4').style.visibility="hidden";
                      document.getElementById('aa1').style.visibility="hidden";
                      document.getElementById('aa2').style.visibility="hidden";
                      document.getElementById('c1').style.visibility="visible";
                      document.getElementById('m-6').style.visibility="visible";
                      document.getElementById('hand1').style.visibility="visible";
                      document.getElementById('p1').style.visibility="visible";
                      myInt = setInterval(function(){ animatearrow(); }, 500);
                      animateArrowATPosition(150,200,20,180);
                      document.getElementById('hand1').onclick=function() { step3(); };
                    }
                   else
                   {
                   document.getElementById('Sample4').style.visibility="visible";
                   document.getElementById('aa1').style.visibility="visible";
                   document.getElementById('aa2').style.visibility="visible";

                    setTimeout(function()
                    {
                      document.getElementById('aa').style.visibility="visible";
                      document.getElementById("aa").src =data8[p][0];
                      document.getElementById('Sample4').style.visibility="hidden";
                      myInt = setInterval(function(){ animatearrow(); }, 500);
                      animateArrowATPosition(125,190,30,-90);
                      document.getElementById('aa').onclick=function() { 
                      myStopFunction();
                      document.getElementById("aa").style.animation = "moveh1 1s ease-in-out  forwards";
                      document.getElementById("aa1").style.animation = "moveh2 1s ease-in-out  forwards";
                      document.getElementById("aa2").style.animation = "moveh3 1s ease-in-out  forwards";
                      setTimeout(function()
                      {
                        document.getElementById('c1').style.visibility="visible";
                        document.getElementById('m-6').style.visibility="visible";
                        document.getElementById('hand1').style.visibility="visible";
                        document.getElementById('p1').style.visibility="visible";
                        myInt = setInterval(function(){ animatearrow(); }, 500);
                        animateArrowATPosition(150,200,20,180);
                        document.getElementById('hand1').onclick=function() { step3(); };
                      },3000);
                    };
                  },3000);
                }
              },2000);
            };
          };
        };
      };
    };
  }
          if (simsubscreennum===4)
          {
            document.getElementById('ax1').style.visibility="hidden";
            document.getElementById('ax2').style.visibility="hidden";
            document.getElementById('aa1').style.visibility="hidden";
            document.getElementById('aa2').style.visibility="hidden";
            document.getElementById('img').style.visibility="hidden";

            document.getElementById('Sample5').style.visibility="hidden";
            document.getElementById('aa').style.visibility="hidden";
            document.getElementById('pipe1').style.visibility="hidden";
            document.getElementById('samp1').style.visibility="hidden";
            document.getElementById('samp2').style.visibility="hidden";
            document.getElementById('manotop').style.visibility="hidden";
            document.getElementById('mover1').style.visibility="hidden";
            document.getElementById('p1').style.visibility="hidden";
            document.getElementById('mover6').style.display="none";
            document.getElementById('p2').style.visibility="hidden";
            fillTable1(0);
            console.log(p)
            highlight();
            p=p-2;
            console.log(p);
            document.getElementById('s1').innerHTML=data11[p][0];
            calc1( 'button','output','output','button','output','button1','button','wrong','wrong','right','button1','h1','h1','output','wrong','right','right','h1','h1','button',0);

            calc1( 'button1','output1','output1','button1','output1','button2','button1','wrong1','wrong1','right1','button2','h2','h2','output1','wrong1','right1','right1','h2','h2','button1',1);

            calc1( 'button2','output2','output2','button2','output2','nextButton','button2','wrong2','wrong2','right2','nextButton','h3','h3','output2','wrong2','right2','right2','h3','h3','button2',2);
          }

          if (simsubscreennum===5)
          {
            refresh('right','right1','right2');
            refresh1('h1','h2','h3');
            fillTable2(0);
            highlight1();
            p=p-1;
            calc2('button2-1','output2-1','output2-1','button2-1','output2-1','button2-2','button2-1','wrong2-1','wrong2-1','right2-1','button2-2','h2-1','h2-1','output2-1','wrong2-1','right2-1','right2-1','h2-1','h2-1','button2-1',0);
            
            calc2('button2-2','output2-2','output2-2','button2-2','output2-2','nextButton','button2-2','wrong2-2','wrong2-2','right2-2','nextButton','h2-2','h2-2','output2-2','wrong2-2','right2-2','right2-2','h2-2','h2-2','button2-2',1);
          }

          if (simsubscreennum===6)
          {
            document.getElementById('right2-1').style.visibility="hidden";
            document.getElementById('right2-2').style.visibility="hidden";
            document.getElementById('h2-1').style.visibility="hidden";
            document.getElementById('h2-2').style.visibility="hidden";   
          }
          if (simsubscreennum===7)
          {
                    document.getElementById('mm').style.visibility="visible";

            document.getElementById('chartContainer').style.visibility = "hidden";
            document.getElementById('download-graph').style.visibility = "hidden";

            myInt = setInterval(function () { animatearrow(); }, 500);
            animateArrowATPosition(245, 220, 20, 270);
            document.getElementById('slider22').onclick=function() { stepp1(); };
          }

          if (simsubscreennum===8)
          {
            document.getElementById('Sample00').style.visibility="hidden";
            //document.getElementById('mm').style.visibility="hidden";
            //document.getElementById('arrows1').style.display = "none";
            display('click11','circle20','circle10','speed11','ndswh1','arrow22','wind1','can-1','can-2','can-3','n-1');
            document.getElementById('m12').style.display = "none";
            document.getElementById('mm').style.display = "none";
            document.getElementById('Sample02').style.display = "none";

            document.getElementById('switch22').style.display = "none";
            document.getElementById('n-2').style.visibility="visible";

            document.getElementById('n-5').style.visibility="visible";
            document.getElementById('pipe_1').style.visibility="visible";
            document.getElementById('bx1').style.visibility="visible";
              document.getElementById('bx2').style.visibility="visible";

                myInt = setInterval(function(){ animatearrow(); }, 500);
                animateArrowATPosition(490,160,30,360);
                document.getElementById('bx2').onclick=function() { 
                myStopFunction();
                document.getElementById('bx2').onclick="";
                document.getElementById('ab12').style.visibility="visible";
                myInt = setInterval(function(){ animatearrow(); }, 500);
                animateArrowATPosition(640,200,30,-90);
                document.getElementById('ab12').onclick=function() { 
                  myStopFunction();
                document.getElementById('ab12').onclick="";
                  document.getElementById('n-1').style.visibility="hidden";
                  document.getElementById('n-2').style.visibility="hidden";
                  document.getElementById('n-5').style.visibility="hidden";
                  document.getElementById('can-1').style.visibility="hidden";
                  document.getElementById('can-2').style.visibility="hidden";
                  document.getElementById('can-3').style.visibility="hidden";
                  
                document.getElementById('ab12').style.visibility="hidden";
                document.getElementById('samp_1').style.visibility="visible";
                document.getElementById('samp_2').style.visibility="visible";
                document.getElementById('img1').style.visibility="visible";

                document.getElementById('manotop1').style.visibility="visible";
                document.getElementById('mover_1').style.visibility="visible";
              setTimeout(function()
              {
              if(p==0)
              {

              document.getElementById('Sample4').style.visibility="hidden";
                document.getElementById('bb1').style.visibility="hidden";
                document.getElementById('bb2').style.visibility="hidden";

                  document.getElementById('c1').style.visibility="visible";
                  //document.getElementById('ab1').style.visibility="visible";
                  document.getElementById('m-6').style.visibility="visible";
                 document.getElementById('hand_1').style.visibility="visible";
                  document.getElementById('p_1').style.visibility="visible";
                  myInt = setInterval(function(){ animatearrow(); }, 500);
                  animateArrowATPosition(150,200,20,180);
                  document.getElementById('hand_1').onclick=function() { step33(); };
              }
              else
              {
              document.getElementById('Sample4').style.visibility="visible";
             
              setTimeout(function()
              {
                document.getElementById('bb1').style.visibility="visible";
                document.getElementById('bb2').style.visibility="visible";
              
                document.getElementById('bb').style.visibility="visible";
                document.getElementById("bb").src =data8[p][0];
                
                document.getElementById('Sample4').style.visibility="hidden";
              
                myInt = setInterval(function(){ animatearrow(); }, 500);
                animateArrowATPosition(125,190,30,-90);
                document.getElementById('bb').onclick=function() { 
                  myStopFunction();
              document.getElementById("bb").style.animation = "moveh1 1s ease-in-out  forwards";
              document.getElementById("bb1").style.animation = "moveh2 1s ease-in-out  forwards";
              document.getElementById("bb2").style.animation = "moveh3 1s ease-in-out  forwards";
                setTimeout(function()
                {
                  document.getElementById('c1').style.visibility="visible";
                  document.getElementById('m-6').style.visibility="visible";
                  document.getElementById('hand_1').style.visibility="visible";
                  document.getElementById('p_1').style.visibility="visible";
                  myInt = setInterval(function(){ animatearrow(); }, 500);
                  animateArrowATPosition(150,200,20,180);
                  document.getElementById('hand_1').onclick=function() { step33(); };
                },3000);
              };
              },3000);
              }
            },2000);
          };
        };
      }

        
          if (simsubscreennum===9)
          {
            document.getElementById('bx1').style.visibility="hidden";
            document.getElementById('bx2').style.visibility="hidden";
            document.getElementById('bb1').style.visibility="hidden";
            document.getElementById('bb2').style.visibility="hidden";
            document.getElementById('Sample5').style.visibility="hidden";
            document.getElementById('bb').style.visibility="hidden";
            document.getElementById('pipe_1').style.visibility="hidden";
            document.getElementById('samp_1').style.visibility="hidden";
            document.getElementById('samp_2').style.visibility="hidden";
            document.getElementById('manotop1').style.visibility="hidden";
            document.getElementById('mover_1').style.visibility="hidden"
            document.getElementById('p_1').style.visibility="hidden";
            document.getElementById('mover_6').style.display="none";
            document.getElementById('p_2').style.visibility="hidden";
            document.getElementById('img1').style.visibility="hidden";

            fillTable3(0);
            highlight2();
            p=p-2;
            document.getElementById('s2').innerHTML=data11[p][0];

            calc3( 'button-11','output-11','output-11','button-11','output-11','button1-11','button-11','wrong-11','wrong-11','right-11','button1-11','h1-2','h1-2','output-11','wrong-11','right-11','right-11','h1-2','h1-2','button-11',0);

            calc3( 'button1-11','output1-11','output1-11','button1-11','output1-11','button2-11','button1-11','wrong1-11','wrong1-11','right1-11','button2-11','h2-21','h2-21','output1-11','wrong1-11','right1-11','right1-11','h2-21','h2-21','button1-11',1);

            calc3( 'button2-11','output2-11','output2-11','button2-11','output2-11','nextButton','button2-11','wrong2-11','wrong2-11','right2-11','nextButton','h3-2','h3-2','output2-11','wrong2-11','right2-11','right2-11','h3-2','h3-2','button2-11',2);

          }
          if (simsubscreennum===10)
          {
            refresh('right-11','right1-11','right2-11');
            refresh1('h1-2','h2-21','h3-2');
            fillTable4(0);
            highlight3();
            p=p-1;
            calc4('button3-1','output3-1','output3-1','button3-1','output3-1','button3-2','button3-1','wrong3-1','wrong3-1','right3-1','button3-2','h3-1','h3-1','output3-1','wrong3-1','right3-1','right3-1','h3-1','h3-1','button3-1',0);

            calc4('button3-2','output3-2','output3-2','button3-2','output3-2','nextButton','button3-2','wrong3-2','wrong3-2','right3-2','nextButton','h3-2','h3-2','output3-2','wrong3-2','right3-2','right3-2','h3-2','h3-2','button3-2',1);
          }

          if (simsubscreennum===11)
          {

            document.getElementById('right3-1').style.visibility="hidden";
            document.getElementById('right3-2').style.visibility="hidden";
            document.getElementById('h3-1').style.visibility="hidden";
            document.getElementById('h3-2').style.visibility="hidden";
          }
          if (simsubscreennum===12)
          {
            document.getElementById('chartContainer1').style.visibility = "hidden";
            document.getElementById('download-graph1').style.visibility = "hidden";
            $("#cbcalculation").ejChart(
          { 
            primaryXAxis:
            {
              title: { text: 'Volume Flow in m\u00B3/s' ,
                  font : { fontWeight : "Bold" ,
                      fontFamily: "Verdana",
                      size: '14px' }},
              labelFormat:"{value}",      
              // range: { min: 1000, max: 4000, interval: 500},              
              range: {min: 0,max: 0.30,interval: 0.05 } ,
              border: { 
                    color: "blue",
                    width: 2,
                    opacity: 0.5 ,
                    cornerRadius : 4
                  }, 

              //Customizing Chart title font 
              font:{ 
                  
                  fontFamily: "Verdana",
                  color: "black",
                  size: '14px' 
                }             
              
            },   
            primaryYAxis:
            {
              title: { text: 'Total Pressure in Pascal' ,
                  font : { fontWeight : "Bold" ,
                      fontFamily: "Verdana",
                      size: '14px' }},
              labelFormat:"{value}",
              // range: { min: 100, max: 400, interval: 50 },                       
              range: { min: 0, max: 6, interval: 1}  ,
              border: { 
                    color: "blue",
                    width: 2,
                    opacity: 1 ,
                    cornerRadius : 4
                  }, 
              font:{ 
                  
                  fontFamily: "Verdana",
                  color: "black",
                  size: '14px' 
                }  
            },
            series: 
            [ 
              {
                points: [
                  {x: 0.007,y: 5.842},
                  {x: 0.028,y: 5.425},
                  {x: 0.044,y: 5.007},
                  {x: 0.133,y: 3.338},
                  {x: 0.257,y: 2.295}
                                ],
                name:'Total Pressure v/s Volume Flow for 300 rpm',
                type: 'line',
                fill:"#0066FF",
                border :{width:5},
                tooltip:{visible:true},
                marker:{
                  shape: 'circle',
                  size:
                  {
                    height: 5, width: 5
                  },
                  visible: true
                },          
                
              },
              {       // Add second series
            points: [
                          {x: 0,y: 0},
                          {x: 0.043,y: 0.417},
                          {x: 0.078,y: 0.417},
                          {x: 0.118,y: 0.522},
                          {x: 0.166,y: 0.835},
                          {x: 0.257,y: 1.252},
                                ],
              name:'Total Pressure v/s Volume Flow for 400 rpm',
              type: 'line',
              fill:"#a04000",
                border :{width:5},
                tooltip:{visible:true},
                marker:{
                  shape: 'circle',
                  size:
                  {
                    height: 5, width: 5
                  },
                  visible: true
                },          
              },
            ],
            commonSeriesOptions : {
              enableAnimation :true,
              animationDuration : 800 
            },
            load:"loadTheme",
            isResponsive: true,
            title :{text: 'Total Pressure v/s Volume Flow'},
            legend:{visible:true,
                font : { fontWeight : "Bold" ,
                fontFamily: "Verdana",
                size: '13px' }}
          });
        }
      }
      function step1() {
        myStopFunction();
        document.getElementById("slider2").onclick = "";
        document.getElementById("slider2").style.animation = "mover 1s ease-in-out  forwards";
        setTimeout(function () {
          document.getElementById('click1').style.visibility = "visible";
          myInt = setInterval(function () { animatearrow(); }, 500);
          animateArrowATPosition(208, 177, 20, 180);
        }, 1000);
        document.getElementById("switch1").onclick = function () { step1_11(); };
      }
    
      function step1_11() {
        myStopFunction();
        document.getElementById("switch1").onclick = "";
        document.getElementById('switch1').style.visibility = "hidden";
        document.getElementById('switch2').style.visibility = "visible";
      
        // var rt = 200;
        document.getElementById('wind').style.visibility = "visible";
        document.getElementById('arrow2').style.visibility = "visible";
        myInt = setInterval(function () { animatearrow(); }, 500);
        animateArrowATPosition(545, 265, 20, -90);
        document.getElementById("cfan1").onclick = function () {
          myStopFunction();
          document.getElementById("cfan1").onclick = "";
          document.getElementById('m11').style.visibility = "visible";
          initiate();
          setInterval("rt(1)", 500);
          setTimeout(function () {
            myInt = setInterval(function () { animatearrow(); }, 500);
            animateArrowATPosition(267, 175, 20, 720);
            document.getElementById("circle4").onclick = function () {
              myStopFunction();
              this.onclick = null;
              document.getElementById('a01').style.visibility = "visible";
              document.getElementById('a01').style.transform = "rotate(380deg)";
              document.getElementById("a01").style.WebkitTransform = "rotate(380deg)";
              document.getElementById("a01").style.msTransform = "rotate(380deg)";
              document.getElementById('Sample0').style.visibility = "visible";
              setTimeout(function () {
                document.getElementById('Sample0').style.visibility = "hidden";
                document.getElementById('a01').style.display = "none";
                myInt = setInterval(function () { animatearrow(); }, 500);
                animateArrowATPosition(267, 150, 20, 720);
                document.getElementById("speed2").onclick = function () {
                  myStopFunction();
                  this.onclick = null;
                  document.getElementById('speed').style.visibility = "visible";
                  document.getElementById('ndswh').style.visibility = "visible";
                  document.getElementById("ndswh").style.animation = "moven 1s ease-in-out forwards";
                  setTimeout(function () {
                    document.getElementById('Sample01').style.visibility = "visible";
                    document.getElementById('speed').style.visibility = "hidden";
                    document.getElementById('ndswh').style.visibility = "hidden";
                    document.getElementById('nextButton').style.visibility = "visible";
                  }, 2000);
                };
              }, 1000);
            };
          }, 1200);
        };
      }
      
        function step2()
        {
          myStopFunction();
          document.getElementById('manometer1').onclick="";
            document.getElementById('ventilationduct2').style.visibility="hidden";
            document.getElementById('ta').style.visibility="hidden";
            document.getElementById('manometer1').style.visibility="hidden";
            document.getElementById('mano').style.visibility="visible";
            document.getElementById('scale').style.visibility="visible";
            document.getElementById('table1').style.visibility="visible";
            myInt = setInterval(function(){ animatearrow(); }, 500);
            animateArrowATPosition(30,120,30,-90);
            document.getElementById('scale').onclick=function() { 
            myStopFunction();
            document.getElementById('scale').onclick="";
            document.getElementById("scale").style.animation = "moves 1s ease-in-out forwards";

          setTimeout(function()
          {
            document.getElementById('12cm').style.visibility="visible";
            document.getElementById('1.7cm').style.visibility="visible";
            setTimeout(function()
            {
              fillTable(0);
              setTimeout(function()
              {
                document.getElementById('12cm').style.visibility="hidden";
                document.getElementById('1.7cm').style.visibility="hidden";
                document.getElementById("scale").style.animation = "movess 1s ease-in-out forwards";
                setTimeout(function()
                {
                  document.getElementById('24cm').style.visibility="visible";
                  document.getElementById('3.2cm').style.visibility="visible";
                  setTimeout(function()
                  {
                    fillTable(1);
                    setTimeout(function()
                    {
                      document.getElementById('24cm').style.visibility="hidden";
                      document.getElementById('3.2cm').style.visibility="hidden";

                      document.getElementById("scale").style.animation = "movese 1s ease-in-out forwards";
                      setTimeout(function()
                      {
                        document.getElementById('30cm').style.visibility="visible";
                        document.getElementById('4cm').style.visibility="visible";

                        setTimeout(function()
                        {
                          fillTable(2);
                          setTimeout(function()
                          {
                            document.getElementById('ca-1').style.visibility="visible";
                            document.getElementById('ca-2').style.visibility="visible";
                            document.getElementById('ca-3').style.visibility="visible";

                            setTimeout(function()
                            {
                              document.getElementById('4cm').style.visibility="hidden";
                              document.getElementById('mano').style.visibility="hidden";
                              document.getElementById('scale').style.visibility="hidden";
                              document.getElementById('30cm').style.visibility="hidden";
                              validateAnswer(0, 1, "150px", "120px");
                            },800);
                          },800);
                        },800);
                      },2000);
                    },2000);
                  },800);
                },2000);
              },2000);
            },800);
          },2000);
        };
      }


        function step3()
        {
          myStopFunction();
          document.getElementById('hand1').onclick="";
          document.getElementById('c1').style.visibility="hidden";
          document.getElementById('m-6').style.visibility="hidden";
          document.getElementById("hand1").style.animation = "movehand1 1s ease-in-out  forwards";
          setTimeout(function()
          {
            document.getElementById("p1").style.animation = "movep 1s ease-in-out  forwards";
            document.getElementById("hand1").style.animation = "movehand11 1s ease-in-out forwards";
            setTimeout(function()
            {
              document.getElementById('Sample1').style.visibility="visible";
              setTimeout(function()
              {
                document.getElementById('Sample1').style.visibility="hidden";
                document.getElementById('hand1').style.visibility="hidden";
                var leftLimbMargin = (data1[p][1]-15)*14.6;
                var rightLimbMargin = (data1[p][2]-15)*14.6;
                document.getElementById('white1').style.marginLeft = leftLimbMargin + 'px';
                document.getElementById('white2').style.marginLeft = rightLimbMargin + 'px';
                setTimeout(function()
                {
                  myInt = setInterval(function(){ animatearrow(); }, 500);
                  animateArrowATPosition(210,385,30,180);
                  document.getElementById("mover1").onclick=function() {
                    myStopFunction();
                    document.getElementById("mover1").onclick="";
                    var boxHandMargin = (data1[p][1]-5)*14.6;
                    //document.getElementById("a3-2").style.marginLeft = boxHandMargin + 'px';
                    document.getElementById("mover1").style.marginLeft = boxHandMargin + 'px';

                    setTimeout(function()
                    {
                      // document.getElementById('a3-2').style.visibility="hidden";
                      document.getElementById('para').innerHTML="Static Head:";
                      document.getElementById('para1').innerHTML="Left Limb Reading="+data1[p][1]+" cm";
                      setTimeout(function()
                      {
                        document.getElementById('mover1').style.display="none";
                        document.getElementById('mover4').style.visibility="visible";
                        setTimeout(function()
                        {
                          // document.getElementById('a41-22').style.visibility="visible";
                          myInt = setInterval(function(){ animatearrow(); }, 500);
                          animateArrowATPosition(210,385,30,180);
                          document.getElementById("mover4").onclick=function() {
                            myStopFunction();
                            document.getElementById("mover4").onclick="";
                            var boxHandMargin = (data1[p][2]-5)*14.6;
                            //document.getElementById("a41-22").style.marginLeft = boxHandMargin + 'px';
                            document.getElementById("mover4").style.marginLeft = boxHandMargin + 'px';

                            setTimeout(function()
                            {
                              //document.getElementById('a41-22').style.visibility="hidden";
                              document.getElementById('para2').innerHTML="Right Limb Reading="+data1[p][2]+" cm";
                              document.getElementById('para3').innerHTML="Difference="+data1[p][3]+" cm";
                              setTimeout(function()
                              {
                                document.getElementById('mover4').style.display="none";
                                display('para','para1','para2','para3','white1','white2','p1','white3','white4','p2','mover2');
                                document.getElementById('hand2').style.visibility="visible";
                                document.getElementById('p2').style.visibility="visible";
                                  document.getElementById('mover2').style.visibility="visible";

                                myInt = setInterval(function(){ animatearrow(); }, 500);
                                animateArrowATPosition(340,170,20,-90);
                                document.getElementById("hand2").onclick=function() {
                                myStopFunction();
                                document.getElementById("hand2").onclick="";
                                document.getElementById("hand2").style.animation = "movehand2 1s ease-in-out forwards";
                                setTimeout(function()
                                {
                                  document.getElementById("p2").style.animation = "movepp 1s ease-in-out forwards";
                                  document.getElementById("hand2").style.animation = "movehand22 1s ease-in-out forwards";

                                  setTimeout(function()
                                  {
                                    document.getElementById('Sample2').style.visibility="visible";
                                    setTimeout(function()
                                    {
                                      document.getElementById('Sample2').style.visibility="hidden";
                                      document.getElementById('hand2').style.visibility="hidden";
                                      var leftLimbMargin = (data1[p][4]-15)*14.6;
                                      var rightLimbMargin = (data1[p][5]-15)*14.6;
                                      document.getElementById('white3').style.marginLeft = leftLimbMargin + 'px';
                                      document.getElementById('white4').style.marginLeft = rightLimbMargin + 'px';

                                      setTimeout(function()
                                      {
                                        myInt = setInterval(function(){ animatearrow(); }, 500);
                                        animateArrowATPosition(210,385,30,180);
                                        document.getElementById("mover2").onclick=function() {
                                          myStopFunction();
                                          var boxHandMargin = (data1[p][4]-5)*14.6;
                                          document.getElementById("mover2").style.marginLeft = boxHandMargin + 'px';
                                          setTimeout(function()
                                          {
                                          document.getElementById('paraa').innerHTML="Total Head:";
                                          document.getElementById('para11').innerHTML="Left Limb Reading="+data1[p][4]+" cm";
                                          setTimeout(function()
                                          {
                                          document.getElementById('mover2').style.display="none";
                                          document.getElementById('mover5').style.visibility="visible";
                                          setTimeout(function()
                                          {
                                          myInt = setInterval(function(){ animatearrow(); }, 500);
                                          animateArrowATPosition(210,385,30,180);
                                          document.getElementById("mover5").onclick=function() {
                                          myStopFunction();
                                          document.getElementById("mover5").onclick="";
                                          var boxHandMargin = (data1[p][5]-5)*14.6;
                                          document.getElementById("mover5").style.marginLeft = boxHandMargin + 'px';
                                          setTimeout(function()
                                          {
                                          document.getElementById('para22').innerHTML="Right Limb Reading="+data1[p][5]+" cm";
                                          document.getElementById('para33').innerHTML="Difference="+data1[p][6]+" cm";
                                          setTimeout(function()
                                          {
                                          document.getElementById('mover5').style.display="none";
                                          display('paraa','para11','para22','para33','white3','white4','mover2','p1','white5','white6','mover3');
                                          setTimeout(function()
                                          {
                                          document.getElementById('Sample3').style.visibility="visible";
                                          setTimeout(function()
                                          {
                                          document.getElementById('Sample3').style.visibility="hidden";
                                          document.getElementById('mover3').style.visibility="visible";

                                          var leftLimbMargin = (data1[p][7]-15)*14.6;
                                          var rightLimbMargin = (data1[p][8]-15)*14.6;
                                          document.getElementById('white5').style.marginLeft = leftLimbMargin + 'px';
                                          document.getElementById('white6').style.marginLeft = rightLimbMargin + 'px';
                                          setTimeout(function()
                                          {
                                          myInt = setInterval(function(){ animatearrow(); }, 500);
                                          animateArrowATPosition(210,385,30,180);
                                          document.getElementById("mover3").onclick=function() {
                                          myStopFunction();
                                          document.getElementById("mover3").onclick="";
                                          boxHandMargin = (data1[p][7]-5)*14.6;
                                          document.getElementById("mover3").style.marginLeft = boxHandMargin + 'px';
                                          setTimeout(function()
                                          {
                                          document.getElementById('para0').innerHTML="Velocity Head:";
                                          document.getElementById('para11-1').innerHTML="Left Limb Reading="+data1[p][7]+" cm";
                                          setTimeout(function()
                                          {
                                          document.getElementById('mover3').style.display="none";
                                          document.getElementById('mover6').style.visibility="visible";
                                          setTimeout(function()
                                          {
                                          myInt = setInterval(function(){ animatearrow(); }, 500);
                                          animateArrowATPosition(210,385,30,180);
                                          document.getElementById("mover6").onclick=function() {
                                          myStopFunction();
                                          document.getElementById("mover6").onclick="";
                                          var boxHandMargin = (data1[p][8]-5)*14.6;
                                          document.getElementById("mover6").style.marginLeft = boxHandMargin + 'px';
                                          setTimeout(function()
                                          {
                                          document.getElementById('para22-1').innerHTML="Right Limb Reading="+data1[p][8]+" cm";
                                          document.getElementById('para33-1').innerHTML="Difference="+data1[p][9]+" cm";
                                          document.getElementById('Sample5').style.visibility="visible";
                                          document.getElementById("ok1").onclick=function() {
                                          document.getElementById("ok1").onclick="";
                                          document.getElementById('ok1').style.visibility="hidden";
                                          document.getElementById('Sample5').style.visibility="hidden";
                                            validateAnswer(1,1, "530px", "90px");
                                          }
                                          },2000);
                                          }
                                        },2000);
                                        },2000);
                                      },2000);
                                      }
                                    },5000)
                                    },3500);
                                  },1000);
                                  },3000);
                                },2000);
                                }
                              },2000);
                              },2000);
                            },2000);
                            }
                          },6000);
                          },3500);
                        },1000);
                        },1000);
                      };
                      },2000);
                    },2000);
                    }
                  },2000);
                  },2000);
                },2000);
                }
              },6000);
              },3500);
            },2000);
            },1000);
          }

    function stepp1() {
      myStopFunction();
      document.getElementById("slider22").onclick = "";
      document.getElementById("slider22").style.animation = "mover 1s ease-in-out  forwards";
      setTimeout(function () {
        document.getElementById('click11').style.visibility = "visible";
        myInt = setInterval(function () { animatearrow(); }, 500);
        animateArrowATPosition(208, 177, 20, 180);
      }, 1000);
      document.getElementById("switch11").onclick = function () { stepp1_11(); };
    }
  
    function stepp1_11() {
      myStopFunction();
      document.getElementById("switch11").onclick = "";
      document.getElementById('switch11').style.visibility = "hidden";
      document.getElementById('switch22').style.visibility = "visible";
    
      // var rt = 200;
      document.getElementById('wind1').style.visibility = "visible";
      document.getElementById('arrow22').style.visibility = "visible";
      myInt = setInterval(function () { animatearrow(); }, 500);
      animateArrowATPosition(545, 265, 20, -90);
      document.getElementById("cfan11").onclick = function () {
        myStopFunction();
        document.getElementById("cfan11").onclick = "";
        document.getElementById('m12').style.visibility = "visible";
        initiate1();
        setInterval("rt1(1)", 500);
        setTimeout(function () {
          myInt = setInterval(function () { animatearrow(); }, 500);
          animateArrowATPosition(267, 175, 20, 720);
          document.getElementById("circle44").onclick = function () {
            myStopFunction();
            this.onclick = null;
            document.getElementById('a02').style.visibility = "visible";
            document.getElementById('a02').style.transform = "rotate(380deg)";
            document.getElementById("a02").style.WebkitTransform = "rotate(380deg)";
            document.getElementById("a02").style.msTransform = "rotate(380deg)";
            document.getElementById('Sample00').style.visibility = "visible";
            setTimeout(function () {
              document.getElementById('Sample00').style.visibility = "hidden";
              document.getElementById('a02').style.display = "none";
              myInt = setInterval(function () { animatearrow(); }, 500);
              animateArrowATPosition(267, 150, 20, 720);
              document.getElementById("speed22").onclick = function () {
                myStopFunction();
                this.onclick = null;
                document.getElementById('speed11').style.visibility = "visible";
                document.getElementById('ndswh1').style.visibility = "visible";
                document.getElementById("ndswh1").style.animation = "movenn 1s ease-in-out forwards";
                setTimeout(function () {
                  document.getElementById('Sample02').style.visibility = "visible";
                  document.getElementById('speed11').style.visibility = "hidden";
                  document.getElementById('ndswh1').style.visibility = "hidden";
                  document.getElementById('nextButton').style.visibility = "visible";
                }, 2000);
              };
            }, 1000);
          };
        }, 1200);
      };
    }
        

        function step33()
        {
          myStopFunction();
          document.getElementById('hand_1').onclick="";
          document.getElementById('c1').style.visibility="hidden";
          // document.getElementById('ab1').style.visibility="hidden";
          // document.getElementById('m-8').style.visibility="hidden";
          // document.getElementById('m-9').style.visibility="hidden";
          document.getElementById('m-6').style.visibility="hidden";
          document.getElementById("hand_1").style.animation = "movehand1 1s ease-in-out  forwards";
          setTimeout(function()
          {
            document.getElementById("p_1").style.animation = "movep 1s ease-in-out  forwards";
            document.getElementById("hand_1").style.animation = "movehand11 1s ease-in-out forwards";
            setTimeout(function()
            {
              document.getElementById('Sample1').style.visibility="visible";
              setTimeout(function()
              {
                document.getElementById('Sample1').style.visibility="hidden";
                document.getElementById('hand_1').style.visibility="hidden";
                var leftLimbMargin = (data3[p][1]-15)*14.6;
                var rightLimbMargin = (data3[p][2]-15)*14.6;
                document.getElementById('white_1').style.marginLeft = leftLimbMargin + 'px';
                document.getElementById('white_2').style.marginLeft = rightLimbMargin + 'px';
                setTimeout(function()
                {
                  // document.getElementById('b3-2').style.visibility="visible";
                  myInt = setInterval(function(){ animatearrow(); }, 500);
                  animateArrowATPosition(210,385,30,180);
                  document.getElementById("mover_1").onclick=function() {
                    myStopFunction();
                    document.getElementById("mover_1").onclick="";
                    var boxHandMargin = (data3[p][1]-5)*14.6;
                    //document.getElementById("b3-2").style.marginLeft = boxHandMargin + 'px';
                    document.getElementById("mover_1").style.marginLeft = boxHandMargin + 'px';
                    setTimeout(function()
                    {
                      // document.getElementById('b3-2').style.visibility="hidden";
                      document.getElementById('par').innerHTML="Static Head:";
                      document.getElementById('par1').innerHTML="Left Limb Reading="+data3[p][1]+" cm";
                      setTimeout(function()
                      {
                        document.getElementById('mover_1').style.display="none";
                        document.getElementById('mover_4').style.visibility="visible";
                        setTimeout(function()
                        {
                          //document.getElementById('b41-22').style.visibility="visible";
                          myInt = setInterval(function(){ animatearrow(); }, 500);
                          animateArrowATPosition(210,385,30,180);
                          document.getElementById("mover_4").onclick=function() {
                            myStopFunction();
                            document.getElementById("mover_4").onclick="";
                            var boxHandMargin = (data3[p][2]-5)*14.6;
                            //document.getElementById("b41-22").style.marginLeft = boxHandMargin + 'px';
                            document.getElementById("mover_4").style.marginLeft = boxHandMargin + 'px';
                            setTimeout(function()
                            {
                              //document.getElementById('b41-22').style.visibility="hidden";
                              document.getElementById('par2').innerHTML="Right Limb Reading="+data3[p][2]+" cm";
                              document.getElementById('par3').innerHTML="Difference="+data3[p][3]+" cm";
                              setTimeout(function()
                              {
                                document.getElementById('mover_4').style.display="none";
                                display('par','par1','par2','par3','white_1','white_2','p_1','white_3','white_4','p_2','mover_2');
                                document.getElementById('hand_2').style.visibility="visible";
                                myInt = setInterval(function(){ animatearrow(); }, 500);
                                animateArrowATPosition(340,170,20,-90);
                                document.getElementById("hand_2").onclick=function() {
                                myStopFunction();
                                document.getElementById("hand_2").onclick="";
                                document.getElementById("hand_2").style.animation = "movehand2 1s ease-in-out forwards";
                                setTimeout(function()
                                {
                                  document.getElementById("p_2").style.animation = "movepp 1s ease-in-out forwards";
                                  document.getElementById("hand_2").style.animation = "movehand22 1s ease-in-out forwards";
                                  setTimeout(function()
                                  {
                                    document.getElementById('Sample2').style.visibility="visible";
                                    setTimeout(function()
                                    {
                                      document.getElementById('Sample2').style.visibility="hidden";
                                      document.getElementById('hand_2').style.visibility="hidden";
                                      var leftLimbMargin = (data3[p][4]-15)*14.6;
                                      var rightLimbMargin = (data3[p][5]-15)*14.6;
                                      document.getElementById('white_3').style.marginLeft = leftLimbMargin + 'px';
                                      document.getElementById('white_4').style.marginLeft = rightLimbMargin + 'px';
                                      setTimeout(function()
                                      {
                                        //document.getElementById('b3-22').style.visibility="visible";
                                        myInt = setInterval(function(){ animatearrow(); }, 500);
                                        animateArrowATPosition(210,385,30,180);
                                        document.getElementById("mover_2").onclick=function() {
                                          myStopFunction();
                                          var boxHandMargin = (data3[p][4]-5)*14.6;
                                          // document.getElementById("b3-22").style.marginLeft = boxHandMargin + 'px';
                                          document.getElementById("mover_2").style.marginLeft = boxHandMargin + 'px';
                                          setTimeout(function()
                                          {
                                          document.getElementById('mover_2').style.display="none";
                                          document.getElementById('parr').innerHTML="Total Head:";
                                          document.getElementById('par11').innerHTML="Left Limb Reading="+data3[p][4]+" cm";
                                          
                                          document.getElementById('mover_5').style.visibility="visible";
                                          setTimeout(function()
                                          {
                                          myInt = setInterval(function(){ animatearrow(); }, 500);
                                          animateArrowATPosition(210,385,30,180);
                                          document.getElementById("mover_5").onclick=function() {
                                          myStopFunction();
                                          document.getElementById("mover_5").onclick="";
                                          var boxHandMargin = (data3[p][5]-5)*14.6;
                                          document.getElementById("mover_5").style.marginLeft = boxHandMargin + 'px';
                                          setTimeout(function()
                                          {
                                          document.getElementById('par22').innerHTML="Right Limb Reading="+data3[p][5]+" cm";
                                          document.getElementById('par33').innerHTML="Difference="+data3[p][6]+" cm";
                                          setTimeout(function()
                                          {
                                          document.getElementById('mover_5').style.display="none";
                                          display('parr','par11','par22','par33','white_3','white_4','mover_2','p_1','white_5','white_6','mover_3');
                                          setTimeout(function()
                                          {
                                          document.getElementById('Sample3').style.visibility="visible";
                                          setTimeout(function()
                                          {
                                          document.getElementById('Sample3').style.visibility="hidden";
                                          var leftLimbMargin = (data3[p][7]-15)*14.6;
                                          var rightLimbMargin = (data3[p][8]-15)*14.6;
                                          document.getElementById('white_5').style.marginLeft = leftLimbMargin + 'px';
                                          document.getElementById('white_6').style.marginLeft = rightLimbMargin + 'px';
                                          setTimeout(function()
                                          {
                                          myInt = setInterval(function(){ animatearrow(); }, 500);
                                          animateArrowATPosition(210,385,30,180);
                                          document.getElementById("mover_3").onclick=function() {
                                          myStopFunction();
                                          document.getElementById("mover_3").onclick="";
                                          boxHandMargin = (data3[p][7]-5)*14.6;
                                          document.getElementById("mover_3").style.marginLeft = boxHandMargin + 'px';
                                          setTimeout(function()
                                          {
                                          document.getElementById('par0').innerHTML="Velocity Head:";
                                          document.getElementById('par12-2').innerHTML="Left Limb Reading="+data3[p][7]+" cm";
                                          setTimeout(function()
                                          {
                                          document.getElementById('mover_3').style.display="none";
                                          document.getElementById('mover_6').style.visibility="visible";
                                          setTimeout(function()
                                          {
                                          myInt = setInterval(function(){ animatearrow(); }, 500);
                                          animateArrowATPosition(210,385,30,180);
                                          document.getElementById("mover_6").onclick=function() {
                                          myStopFunction();
                                          document.getElementById("mover_6").onclick="";
                                          var boxHandMargin = (data3[p][8]-5)*14.6;
                                          document.getElementById("mover_6").style.marginLeft = boxHandMargin + 'px';
                                          setTimeout(function()
                                          {
                                          document.getElementById('par22-2').innerHTML="Right Limb Reading="+data3[p][8]+" cm";
                                          document.getElementById('par33-2').innerHTML="Difference="+data3[p][9]+" cm";
                                          document.getElementById('Sample55').style.visibility="visible";
                                          document.getElementById("ok2").onclick=function() {
                                          document.getElementById("ok2").onclick="";
                                          document.getElementById('ok2').style.visibility="hidden";
                                          document.getElementById('Sample55').style.visibility="hidden";
                                          document.getElementById('nextButton').style.visibility = "visible";
                                          }
                                          },2000);
                                          }
                                        },2000);
                                        },2000);
                                      },2000);
                                      }
                                    },5000)
                                    },3500);
                                  },1000);
                                  },3000);
                                },2000);
                                }
                              },2000);
                            },2000);
                            }
                          },6000);
                          },3500);
                        },1000);
                        },1000);
                      };
                      },2000);
                    },2000);
                    }
                  },2000);
                  },2000);
                },2000);
                }
              },6000);
              },3500);
            },2000);
            },1000);
          }

        function refresh(r1,r2,r3)
        {
          document.getElementById(r1).style.visibility="hidden";
          document.getElementById(r2).style.visibility="hidden";
          document.getElementById(r3).style.visibility="hidden";
        }
        function refresh1(n1,n2,n3)
        {
          document.getElementById(n1).style.display="none";
          document.getElementById(n2).style.display="none";
          document.getElementById(n3).style.display="none";
        }
        function display(para_1,para_2,para_3,para_4,para_5,para_6,para_7,para_8,para_9,para_10,para_11)
        {
          document.getElementById(para_1).style.visibility="hidden";
          document.getElementById(para_2).style.visibility="hidden";
          document.getElementById(para_3).style.visibility="hidden";
          document.getElementById(para_4).style.visibility="hidden";
          document.getElementById(para_5).style.visibility="hidden";
          document.getElementById(para_6).style.visibility="hidden";
          document.getElementById(para_7).style.visibility="hidden";
          document.getElementById(para_8).style.visibility="visible";
          document.getElementById(para_9).style.visibility="visible";
          document.getElementById(para_10).style.visibility="visible";
          document.getElementById(para_11).style.visibility="visible";
        }

        var k;
        function calc1(para_button,para_output,para_output,para_button,para_output,
          para_button1,para_button,para_wrong,para_wrong,para_right,para_button1,
          para_h1,para_h1,para_output,para_wrong,para_right,para_right,para_h1,para_h1,para_button,k )
        {
      //    console.log(p);
          var flag1=0;
          document.getElementById(para_button).onclick=function() {
            n= document.getElementById(para_output).value;
            if(document.getElementById(para_output).value==="")
            {
              if(document.getElementById(para_button).innerHTML==="Result"){
                document.getElementById(para_output).value=data5[p][k];
                document.getElementById(para_button1).style.visibility="visible";
                document.getElementById(para_button).style.visibility = "hidden";
                document.getElementById(para_wrong).style.visibility = "hidden";
              }
              else
                alert("Enter the value to proceed");
            }
            else {
              if ((Math.floor(n * 10) === Math.floor(data5[p][k] * 10)) || (Math.floor(n * 100) === Math.floor(data5[p][k] * 100)))
              {
                document.getElementById(para_button).style.visibility = 'hidden';
                document.getElementById(para_wrong).style.visibility = "hidden";
                document.getElementById(para_right).style.visibility = "visible";
                document.getElementById(para_button1).style.visibility = 'visible';
                document.getElementById(para_h1).style.visibility="visible";
                document.getElementById(para_h1).innerHTML=data5[p][k];}
                else{
                  flag1+=1;
                  document.getElementById(para_output).value = "";
                  document.getElementById(para_wrong).style.visibility = "visible";
                  document.getElementById(para_right).style.visibility = "hidden";
                  if (flag1===2){
                    if ((Math.floor(n * 10) === Math.floor(data5[p][k] * 10)) || (Math.floor(n * 100) === Math.floor(data5[p][k] * 100)))

                    {
                      document.getElementById(para_right).style.visibility="visible";
                      document.getElementById(para_h1).style.visibility="visible";
                      document.getElementById(para_h1).innerHTML=data5[p][k];
                    }
                    else
                      document.getElementById(para_button).innerHTML="Result";
                  }
                }
              }
            };
          }

          var k;
          function calc2(para_button1,para_output1,para_output1,para_button1,para_output1,para_button11,
            para_button1,para_wrong1,para_wrong1,para_right1,para_button11,para_h11,para_h11,para_output1,
            para_wrong1,para_right1,para_right1,para_h11,para_h11,para_button1,k)
          {
            var flag1=0;
            document.getElementById(para_button1).onclick=function() {
              n= document.getElementById(para_output1).value;
              if(document.getElementById(para_output1).value==="")
              {
                if(document.getElementById(para_button1).innerHTML==="Result"){
                  document.getElementById(para_output1).value=data2_1[p][k];
                  document.getElementById(para_button11).style.visibility="visible";
                  document.getElementById(para_button1).style.visibility = "hidden";
                  document.getElementById(para_wrong1).style.visibility = "hidden";
                }
                else
                  alert("Enter the value to proceed");
              }
              else {
                if ((Math.floor(n * 10) === Math.floor(data2_1[p][k] * 10)) || (Math.floor(n * 100) === Math.floor(data2_1[p][k] * 100)))
              {
                  document.getElementById(para_button1).style.visibility = 'hidden';
                  document.getElementById(para_wrong1).style.visibility = "hidden";
                  document.getElementById(para_right1).style.visibility = "visible";
                  document.getElementById(para_button11).style.visibility = 'visible';
                  document.getElementById(para_h11).style.visibility="visible";
                  document.getElementById(para_h11).innerHTML=data2_1[p][k];
                }
                  else{
                    flag1+=1;
                    document.getElementById(para_output1).value = "";
                    document.getElementById(para_wrong1).style.visibility = "visible";
                    document.getElementById(para_right1).style.visibility = "hidden";
                    if (flag1===2){
                      if ((Math.floor(n * 10) === Math.floor(data2_1[p][k] * 10)) || (Math.floor(n * 100) === Math.floor(data2_1[p][k] * 100)))
                      {
                        document.getElementById(para_right1).style.visibility="visible";
                        document.getElementById(para_h11).style.visibility="visible";
                        document.getElementById(para_h11).innerHTML=data2_1[p][k];
                      }
                      else
                        document.getElementById(para_button1).innerHTML="Result";
                    }
                  }
                }
              };
            }

            var k;
            function calc3(para_button2,para_output2,para_output2,para_button2,para_output2,para_button12,
              para_button2,para_wrong2,para_wrong2,para_right2,para_button12,para_h2,para_h2,para_output2,
              para_wrong2,para_right2,para_right2,para_h2,para_h2,para_button2,k )
            {
              var flag1=0;
              document.getElementById(para_button2).onclick=function() {
                n= document.getElementById(para_output2).value;
                if(document.getElementById(para_output2).value==="")
                {
                  if(document.getElementById(para_button2).innerHTML==="Result"){
                    document.getElementById(para_output2).value=data7[p][k];
                    document.getElementById(para_button12).style.visibility="visible";
                    document.getElementById(para_button2).style.visibility = "hidden";
                    document.getElementById(para_wrong2).style.visibility = "hidden";
                  }
                  else
                    alert("Enter the value to proceed");
                }
                else {
                  if ((Math.floor(n * 10) === Math.floor(data7[p][k] * 10)) || (Math.floor(n * 100) === Math.floor(data7[p][k] * 100)))
                  
                  {
                    document.getElementById(para_button2).style.visibility = 'hidden';
                    document.getElementById(para_wrong2).style.visibility = "hidden";
                    document.getElementById(para_right2).style.visibility = "visible";
                    document.getElementById(para_button12).style.visibility = 'visible';
                    document.getElementById(para_h2).style.visibility="visible";
                    document.getElementById(para_h2).innerHTML=data7[p][k];}
                    else{
                      flag1+=1;
                      document.getElementById(para_output2).value = "";
                      document.getElementById(para_wrong2).style.visibility = "visible";
                      document.getElementById(para_right2).style.visibility = "hidden";
                      if (flag1===2){
                        if ((Math.floor(n * 10) === Math.floor(data7[p][k] * 10)) || (Math.floor(n * 100) === Math.floor(data7[p][k] * 100)))
                        {
                          document.getElementById(para_right2).style.visibility="visible";
                          document.getElementById(para_h2).style.visibility="visible";
                          document.getElementById(para_h2).innerHTML=data7[p][k];
                        }
                        else
                          document.getElementById(para_button2).innerHTML="Result";
                      }
                    }
                  }
                };
              }

              var k;
              function calc4(para_button3,para_output3,para_output3,para_button3,para_output3,para_button13,
                para_button3,para_wrong3,para_wrong3,para_right3,para_button13,para_h3,para_h3,para_output3,
                para_wrong3,para_right3,para_right3,para_h3,para_h3,para_button3,k )
              {
                var flag1=0;
                document.getElementById(para_button3).onclick=function() {
                  n= document.getElementById(para_output3).value;
                  if(document.getElementById(para_output3).value==="")
                  {
                    if(document.getElementById(para_button3).innerHTML==="Result"){
                      document.getElementById(para_output3).value=data4_1[p][k];
                      // document.getElementById(rs5).innerHTML=data4_1[p][k];
                      document.getElementById(para_button13).style.visibility="visible";
                      document.getElementById(para_button3).style.visibility = "hidden";
                      document.getElementById(para_wrong3).style.visibility = "hidden";
                    }
                    else
                      alert("Enter the value to proceed");
                  }
                  else {
                    if ((Math.floor(n * 10) === Math.floor(data4_1[p][k] * 10)) || (Math.floor(n * 100) === Math.floor(data4_1[p][k] * 100)))
                    {
                      document.getElementById(para_button3).style.visibility = 'hidden';
                      document.getElementById(para_wrong3).style.visibility = "hidden";
                      document.getElementById(para_right3).style.visibility = "visible";
                      document.getElementById(para_button13).style.visibility = 'visible';
                      document.getElementById(para_h3).style.visibility="visible";
                      document.getElementById(para_h3).innerHTML=data4_1[p][k];
                    // document.getElementById(rs5).innerHTML=data4_1[p][k];
                  }

                      else{
                        flag1+=1;
                        document.getElementById(para_output3).value = "";
                        document.getElementById(para_wrong3).style.visibility = "visible";
                        document.getElementById(para_right3).style.visibility = "hidden";
                        if (flag1===2){
                          if ((Math.floor(n * 10) === Math.floor(data4_1[p][k] * 10)) || (Math.floor(n * 100) === Math.floor(data4_1[p][k] * 100)))
                          {
                            document.getElementById(para_right3).style.visibility="visible";
                            document.getElementById(para_h3).style.visibility="visible";
                            document.getElementById(para_h3).innerHTML=data4_1[p][k];
                            //document.getElementById(rs5).innerHTML=data4_1[p][k];
                          }
                          else
                            document.getElementById(para_button3).innerHTML="Result";
                        }
                      }
                    }
                  };
                }


                function graph() {
                    document.getElementById('chartContainer').style.visibility = "visible";
                    document.getElementById('download-graph').style.visibility = "visible";

                    $("#chartContainer").ejChart({
                        primaryXAxis: {
                            title: {
                                text: 'Volume Flow in m\u00B3/s',
                                font: {
                                    fontWeight: "Bold",
                                    fontFamily: "Verdana",
                                    size: '14px'
                                }
                            },
                            labelFormat: "{value}",
                            // range: { min: 1000, max: 4000, interval: 500},              
                            range: {
                                min: 0,max: 0.30,interval: 0.05
                            },
                          border: { 
                              color: "blue",
                              width: 2,
                              opacity: 0.5 ,
                              cornerRadius : 4
                            }, 


                            //Customizing Chart title font 
                            font: {
                                fontFamily: "Verdana",color: "black",size: '14px'
                            }
                        },
                        primaryYAxis: {
                            title: {
                                text: 'Total Pressure in Pascal',
                                font: {
                                    fontWeight: "Bold",fontFamily: "Verdana",size: '14px'
                                }
                            },
                            labelFormat: "{value}",
                            // range: { min: 100, max: 400, interval: 50 },                       
                            range: {
                                min: 0,max: 6,interval: 1
                            },
                            border: { 
                              color: "blue",
                              width: 2,
                              opacity: 0.5 ,
                              cornerRadius : 4
                            }, 

                            font: {
                                fontFamily: "Verdana",color: "black",size: '14px'
                            }

                        },
                        series: [{
                                points: [
                                  {x: 0.007,y: 5.842},
                                  {x: 0.028,y: 5.425},
                                  {x: 0.044,y: 5.007},
                                  {x: 0.133,y: 3.338},
                                  {x: 0.257,y: 2.295}
                                ],
                                name: 'Total Pressure v/s Volume Flow',
                                type: 'line',
                                fill: "#0066FF",
                                border: {
                                    width: 5
                                },
                                tooltip: {
                                    visible: true
                                },
                                marker: {
                                    shape: 'circle',
                                    size: {
                                        height: 5,
                                        width: 5
                                    },
                                    visible: true
                                },
                            },
                        ],
                        commonSeriesOptions: {
                            enableAnimation: true,
                            animationDuration: 800
                        },
                        load: "loadTheme",
                        isResponsive: true,
                        legend: {
                            visible: true,
                            font: {
                                fontWeight: "Bold",
                                fontFamily: "Verdana",
                                size: '12px'
                            }
                        },
                        // enableCanvasRendering: true,
                        exportSettings: { type: "jpg", mode: "client"}
                      
                    });
                    
                    setTimeout(function() {
                        document.getElementById("nextButton").style.visibility = "visible";
                    }, 1000);
                    //Add download function to the anchor element.
                    document.getElementById('download-graph').onclick = function download() {
                        $("#chartContainer").ejChart({enableCanvasRendering:true})
                        var chart = $("#chartContainer").ejChart("export");
                        if(window.navigator.msSaveOrOpenBlob)
                          window.navigator.msSaveOrOpenBlob(chart.msToBlob(), "Graph for 300 rpm.jpg");
                        else{
                          var chartData = chart.toDataURL();
                          this.download = "Graph for 300 rpm.jpg";
                          this.href = chartData;
                        }
                    $("#chartContainer").ejChart({enableCanvasRendering:false})

                    }
                }

              function graph1() {
                    document.getElementById('chartContainer1').style.visibility = "visible";
                    document.getElementById('download-graph1').style.visibility = "visible";
                    $("#chartContainer1").ejChart({
                        primaryXAxis: {
                            title: {
                                text: 'Volume Flow in m\u00B3/s',
                                font: {
                                    fontWeight: "Bold",
                                    fontFamily: "Verdana",
                                    size: '14px'
                                }
                            },
                            labelFormat: "{value}",
                            // range: { min: 1000, max: 4000, interval: 500},              
                            range: {
                                min: 0,max: 0.30,interval: 0.05
                            },
                            border: {
                                color: "blue",width: 2,opacity: 0.5,cornerRadius: 4
                            },
                            //Customizing Chart title font 
                            font: {
                                fontFamily: "Verdana",color: "black",size: '14px'
                            }
                        },
                        primaryYAxis: {
                            title: {
                                text: 'Total Pressure in Pascal',
                                font: {
                                    fontWeight: "Bold",fontFamily: "Verdana",size: '14px'
                                }
                            },
                            labelFormat: "{value}",
                            // range: { min: 100, max: 400, interval: 50 },                       
                            range: {
                                min: 0,max: 6,interval: 1
                            },
                            font: {
                                fontFamily: "Verdana",color: "black",size: '14px'
                            }
                        },
                        series: [{
                                points: [
                                  {x: 0,y: 0},
                                  {x: 0.043,y: 0.417},
                                  {x: 0.078,y: 0.417},
                                  {x: 0.118,y: 0.522},
                                  {x: 0.166,y: 0.835},
                                  {x: 0.257,y: 1.252},
                                ],
                                name: 'Total Pressure v/s Volume Flow',
                                type: 'line',
                                fill: "#a04000",
                                border: {
                                    width: 5
                                },
                                tooltip: {
                                    visible: true
                                },
                                marker: {
                                    shape: 'circle',
                                    size: {
                                        height: 5,
                                        width: 5
                                    },
                                    visible: true
                                },
                            },
                        ],
                        commonSeriesOptions: {
                            enableAnimation: true,
                            animationDuration: 800
                        },
                        load: "loadTheme",
                        isResponsive: true,
                        legend: {
                            visible: true,
                            font: {
                                fontWeight: "Bold",
                                fontFamily: "Verdana",
                                size: '12px'
                            }
                        },
                      // enableCanvasRendering: true,
                        exportSettings: { type: "jpg", mode: "client"}
                    });
                    
                    setTimeout(function() {
                        document.getElementById("nextButton").style.visibility = "visible";
                    }, 1000);

                    //Add download function to the anchor element.
                    document.getElementById('download-graph1').onclick = function download() {
                        $("#chartContainer1").ejChart({enableCanvasRendering:true})

                        var chart = $("#chartContainer1").ejChart("export");
                        if(window.navigator.msSaveOrOpenBlob)
                          window.navigator.msSaveOrOpenBlob(chart.msToBlob(), "Graph for 400 rpm.jpg");
                        else{
                          var chartData = chart.toDataURL();
                          this.download = "Graph for 400 rpm.jpg";
                          this.href = chartData;
                        }
                        $("#chartContainer1").ejChart({enableCanvasRendering:false})
                    }
                }


                function initiate() {
                  var l = 667;
                  var t = 70;
                  var m1 = document.getElementById('m1');
                  m1.style.top = (t + 39) + 'px'; m1.style.left = (l + 4) + 'px';
                  document.getElementById('m2').style.top = (t + 58) + 'px';
                  document.getElementById('m2').style.left = (l + 5) + 'px';
                  document.getElementById('m3').style.top = (t + 73) + 'px';
                  document.getElementById('m3').style.left = (l + 6) + 'px';
                  document.getElementById('m4').style.top = (t + 88) + 'px';
                  document.getElementById('m4').style.left = (l + 7) + 'px';
                  document.getElementById('m5').style.top = (t + 105) + 'px';
                  document.getElementById('m5').style.left = (l + 7) + 'px';
                  // document.getElementById('m6').style.top=(t+110)+'px';
                  // document.getElementById('m6').style.left=(l+8)+'px';
                }
                function rt(n) {
                  var t = 200;
                  while (n) {
                    for (let i = 5; i > 0; i--) {
                      blink(i, t);
                      t += 200;
                    }
                    n--;
                  }
                }
                function blink(i, t) {
                  setTimeout(function () { document.getElementById('m' + i).style.opacity = '1'; }, t);
                  setTimeout(function () { document.getElementById('m' + i).style.opacity = '0'; }, t + 200);
                }
                
                function initiate1() {
                  var l1 = 667;
                  var t1 = 70;
                  var n1 = document.getElementById('n1');
                  n1.style.top = (t1 + 39) + 'px'; n1.style.left = (l1 + 4) + 'px';
                  document.getElementById('n2').style.top = (t1 + 58) + 'px';
                  document.getElementById('n2').style.left = (l1 + 5) + 'px';
                  document.getElementById('n3').style.top = (t1 + 73) + 'px';
                  document.getElementById('n3').style.left = (l1 + 6) + 'px';
                  document.getElementById('n4').style.top = (t1 + 88) + 'px';
                  document.getElementById('n4').style.left = (l1 + 7) + 'px';
                  document.getElementById('n5').style.top = (t1 + 105) + 'px';
                  document.getElementById('n5').style.left = (l1 + 7) + 'px';
                  // document.getElementById('m6').style.top=(t+110)+'px';
                  // document.getElementById('m6').style.left=(l+8)+'px';
                }
                function rt1(n) {
                  var t = 200;
                  while (n) {
                    for (let i = 5; i > 0; i--) {
                      blink1(i, t);
                      t += 200;
                    }
                    n--;
                  }
                }
                function blink1(i, tx) {
                  setTimeout(function () { document.getElementById('n' + i).style.opacity = '1'; }, tx);
                  setTimeout(function () { document.getElementById('n' + i).style.opacity = '0'; }, tx + 150);
                }